name: Test coverage CI

on:
  push:
    branches: ["main", "development"]
  pull_request:
    branches: ["main", "development"]

jobs:
  test-codecov:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 42
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-latest, windows-latest]
        node-version: [16.x, 18.x, 19.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test using Node.js  ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run tests and collect coverage
        run: npm run test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

  finish-codecov: 
    needs: test-codecov
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 42
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-latest, windows-latest]
        node-version: [16.x, 18.x, 19.x]
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v1.1.0
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true

  test-coveralls:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 42
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          version: 10.x
      - run: npm install
      - run: npm run test
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.0
        env:
          NODE_COVERALLS_DEBUG: 1
        with:
          github-token: ${{ secrets.github_token }}
          parallel: true
          flag-name: run-${{ matrix.test_number }}

  finish-coveralls:
    needs: test-coveralls
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 42
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-latest, windows-latest]
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v1.1.0
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true

  